### ISSUE TITLE
Mac pro with two processors

### ISSUE THREAD

**Issue by atisharma** [dgraziotin/mbpfan#152]
Since /sys/devices/platform/coretemp.0/hwmon/hwmon is monitored, if there is a coretemp.1, it is ignored.
It would be nice if both were monitored and the maximum taken.
The same issue applies with multiple fans which have different maximum rpm.

**Comment by atisharma** [comment]
Is this what the multicore branch does?

**Comment by gaul** [comment]
I believe that the multicore branch merely averages the sensors from an individual CPU:

https://github.com/dgraziotin/mbpfan/commit/3ff1aad95f63d8802fcfb58be3a6e204ef5a2a48

**Comment by vuori** [comment]
If you're going to work on this, it would also useful to add configurability regarding which fans to control by label. On a MacPro4,1, just controlling the `EXHAUST` and `INTAKE` fans and letting the SMC take care of the rest seems totally sufficient for CPU-bound loads. Touching `PCI` and `PS` fans is unnecessary and `BOOSTA`/`BOOSTB` (heatsink fans) should be adjusted with a different RPM since they are a lot smaller than the other fans.

**Comment by atisharma** [comment]
@vuori that's a good idea, but would be best treated separately, since I'm not sure how to do this. Would you mind opening another issue please?

**Comment by atisharma** [comment]
@gaul I think I have solved this issue with [PR 165](https://github.com/dgraziotin/mbpfan/pull/165).

**Comment by atisharma** [comment]
Thanks @gaul.
