### ISSUE TITLE
Shutting down fans

### ISSUE THREAD

**Issue by SicVolo** [dgraziotin/mbpfan#61]
Works great on ubuntu 15.04 with kernel 3.19 on MBP 12,1 (early 2015). Thank you! There is one annoying issue thought.
The default EFI ACPI is able to turn off the fan completely when the CPU temp is below 60. MBPFAN does not understand 0 as a min value though. If I set it to '1' it keeps the fan running all the time at 800RPM (probably the min the fan can handle). 
Having the fan running continuously shortens the fan life and drains the battery unnecessarily.

**Comment by dgraziotin** [comment]
I've also recently got a MBP 12,1. Still trying to allocate some time to install Ubuntu on it. Now, you are giving a great suggestion here that seems compatible with [mbpfan original philosophy](http://allanmcrae.com/2010/05/simple-macbook-pro-fan-daemon/). Yet, we must proceed carefully here in order to stick with the philosophy, that is:

- Keep the fan low up to a certain threshold
- Exponentially increase the fan speed over the threshold
- Slowly decrease the fan speed when the temperature goes down

That was for sparing some battery time and for avoiding the much hated sudden lift-off effect.

Now, you suggestion is to shut down the fan when the CPU temp is below 60. How would you fit that into the picture? Here are the possible issues that come out of my head right now:

1. Shutting down the fan below 60 (or whatever threshold we decide) might cause big spikes in temperature according to usage; therefore, the much hated lift-off effect might come back in. An approach would be to shut down below 60, keep the fan at minimum between 60 and, say, 65, then let the algorithm work as usual. We might try this out but the threshold values might change drastically across the various MPB models.

2. Now, I am by no way expert on the history of CPUs, but I've noticed that this much beloved shutting down of the fans has started somewhere between the MBP 8,2 (which I had, and it did not behave like that) and the 11,1 models (which my university provided me one year ago). I wonder if the capability to stick without fans for a while is sustainable by the latest CPUs only.

What are your thoughts on these points? Thank you again for this suggestion.

**Comment by SicVolo** [comment]
I ran sensors on my MBP ubuntu without the fan daemon and saw that EFI keeps the fan completely turned off when the system is in low usage, with no adverse effect on the cpu temp. It seems to me that the thermal profile of the early 2015 MBP is better than the previous generations. So, shutting the fan off below 60, having a minimum between 60 and 68 would be a good approach. 

However I also noticed that under 100% CPU usage, EFI allowed the CPU temp to spike above 100C (yes, that much), tripping the kernel's MCE protection, which forced the reduction of the CPU frequency. I am not sure this is an intended behavior - can you see if that's the same under OSX? I felt OSX does a great job on keeping the noise down on MBP, while controlling the higher end temperatures.
BTW I've used this guide for getting 15.04 ubuntu running on 12,1 - http://tech.ivkin.net/wiki/Linux_and_Unix_How_To#How_to_install_Ubuntu_15.10_on_an_early_2015_MacBook_Pro_.28Retina_12.2C1.29_with_full_disk_encryption

**Comment by dgraziotin** [comment]
Alright, so I logged the temperature and the fan speed of the MBP using OS X 10.10.3 for about 1 hour, using [this R script](https://gist.github.com/dgraziotin/9fda0e2bdf0befed19cf) and @Chris911 [iStats](https://github.com/Chris911/iStats) (nice work!)

Here is a [CSV with the logged values](https://dl.dropboxusercontent.com/u/3366835/mbpfan/mbp.2015.cpu.temp.fan.speed.csv).

Here is a quick chart of the values

![mbp 2015 cpu temp fan speed](https://cloud.githubusercontent.com/assets/153179/7489881/9e619fe6-f3db-11e4-9b35-52ebc9e4bb0a.png)

Some comments:
- The polling interval for logging was set to 5 seconds
- Fan speed is divided by 100 so that the points look closer
- At point 0, the MBP had just booted, so it was fresh
- Usage was real-like, "office" mode (browsing, writing). However, I caused the spike in temperature near time=400 using a series of ```yes``` and ```openssl speed```.
- I plotted points instead of lines, so that we can observe that the MBP fan jumps from 0 RPM to ~1280 RPM "immediately"

Here are my preliminary conclusions from this exploration.
1. The MPB is conservative regarding the fan speed when cold booted. It will try to keep the fan off when the temperature is below 60 AND when it spikes shortly above 60
2. The fan either turned on first either
- When hitting the threshold of 63.8 degrees (never reached in the values prior to starting the fan)
- OR when the temperature stayed around 60 for "a while" (to be determined). The 10 measurements (50 seconds) before the fan started spinning were:

![image](https://cloud.githubusercontent.com/assets/153179/7490282/2f412560-f3df-11e4-886a-357af523e219.png)

3. However, the temperature stayed below 60 for a while right after the fan started spinning. It reached 50 degrees twice and dropped to 45.7 right before I started causing a high temperature. The fan never stopped during this long interval. Here are the last measurements right before the fan stopped

![image](https://cloud.githubusercontent.com/assets/153179/7490276/24f6dafa-f3df-11e4-8d82-81ec22842896.png)
4. Right after these measurements, the fan stopped for a short time. 

![image](https://cloud.githubusercontent.com/assets/153179/7490270/1edd9d52-f3df-11e4-858f-5818d5c69649.png)

The fan either turned on here either
- When hitting a threshold near 45.8 degrees (but right before it was 45.7 and the fan was spinning!)
- When staying below ~46 degrees for a while

5. When I quit causing overheating, the temperature settled between 40 and 50 degrees. The fan stayed on and near 1280 RPM.

Therefore, 
- 1280-1300 RPM is the baseline for this MBP
- 0 RPM is possible but either right after cold booting or for short periods of time. What causes the fan to stop spinning is not very clear.

@SicVolo what are your thoughts on this? I wonder if the effort required to find out the threshold for 0 RPM pays off, as the MBP does not tend to keep the fan off very often.

**Comment by Matthias46** [comment]
Just to make a point:

I strongly suggest to shut down the fan only on the latest Macbook Pro (Early 2015) because it has the Broadwell CPU. The refresh of Haswell, only manufactured at 14nm instead of 22nm.

Haswell Macbook Pro's should keep the fan rotating all the time at a low low rpm. That difference in manufacturing is very significant and practically only Broadwell and next Skylake CPU could shut down the fan!

**Comment by dgraziotin** [comment]
To further elaborate on @Matthias46 comment, in case we decide to let mbpfan shut down the fans, there should be two different cooling algorithms in place. One is the current one, which is for Haswell and before models. The new one would work for Broadwell and the future generations.

**Comment by Matthias46** [comment]
I think that if it is possible and not too much difficult, is worth to let mbfan shut down the fans because this CPU could work fanless in a lot of situation where having the fan at 0 rpm leads to more comfort and more battery life:

- heavy writing
- light browser usage (without flash videos, just reading things and browsing normally)
- video watching (but keep in mind, only with Quicktime that is much more optimized than other videoplayers like VLC. And is important also to use mp4 formats that are hardware accelerated by Quicktime. Using MKV, AVI or other containers, even in low resolutions, leads to a lot of CPU usage and also heat!

**Comment by SicVolo** [comment]
@dgraziotin. Great work with R and iStat, Dan. 
Based on the CSV you captured it seems that OSX's fan controller does not just depend on the current CPU temperature, but uses the CPU **load** factor. It seems to anticipate the CPU temperature based on how busy the CPU is right now, and adjusts the fan accordingly. It also seems to keep the fan running longer even after the CPU temperature got below the threshold, possibly to dissipate heat transferred to the motherboard/case.
That would explain the short shut off of the fan before your stress testing.

Can you do the capture again adding the CPU load into the mix? 

BTW There is only one fan on the early 2015 MBP.

**Comment by dgraziotin** [comment]
I am closing this issue for now. I will consider this issue in the future. Just do not have the time now.
